/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: M5ov092D2MNTEWawzxoFMW8L+0K6eM29kykZHI0J+liBBRKt5M9ucmPc3DOjPtQr0Qb4vtzeatsvpFuShqakpg==
 */

/* eslint-disable */
// tslint:disable

import Cart, {Cart_InsertParameters} from './cart'
import CartItem, {CartItem_InsertParameters} from './cart_item'
import SubscriptionCheckpoint, {SubscriptionCheckpoint_InsertParameters} from './subscription_checkpoint'

interface DatabaseSchema {
  cart: {record: Cart, insert: Cart_InsertParameters};
  cart_item: {record: CartItem, insert: CartItem_InsertParameters};
  subscription_checkpoint: {record: SubscriptionCheckpoint, insert: SubscriptionCheckpoint_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Cart,
  CartItem,
  CartItem_InsertParameters,
  Cart_InsertParameters,
  SubscriptionCheckpoint,
  SubscriptionCheckpoint_InsertParameters,
}
